config/routes.rb
Rails.application.routes.draw do
  
  root "records#new"
  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"
  get "signup", to: "users#new"

  resources :records, only: %i[index show new create update destroy]
  resources :users, only: %i[new create]
  get "games", to: "games#index"
  namespace :settings do
    get "statistics", to: "statistics#index"
    resources :wishlists, only: %i[index show create update destroy]
    get "notifications", to: "notifications#edit"
    patch "notifications", to: "notifications#update"
    get "terms", to: "terms#index"
    get "inquiry", to: "inquiry#new"
    post "inquiry", to: "inquiry#create"
  end
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class = "alert alert-danger">
    <ul class = "mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%=link_to "BILLING NOTEBOOK", root_path, class: "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if logged_in? %>
          <li class="nav-item">
            <p class="nav-link mb-0"><%=current_user.name%></p>
          </li>
          <li class="nav-item">
            <%= link_to t('defaults.settings'), settings_statistics_path, class: "nav-link mb-0" %>
          </li>
          <li class="nav-item">
            <%= link_to t('defaults.logout'), logout_path, data: { turbo_method: :delete }, class: "nav-link mb-0" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to t('defaults.login'), login_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to t('defaults.signup'), signup_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_settings_tab.html.erb
<div class="nav flex-column nav-pills" id="v-pills-settings-tab" role="tablist" aria-orientation="vertical">
  <a href=<%=settings_statistics_path%> class="nav-link" id="v-pills-statistics-tab" role="tab" aria-controls="v-pills-statistics" aria-selected="false">統計</a>
  <a href=<%=settings_wishlists_path%> class="nav-link" id="v-pills-wishlists-tab" role="tab" aria-controls="v-pills-wishlists" aria-selected="false">ほしい物リスト</a>
  <a href=<%=settings_notifications_path%> class="nav-link" id="v-pills-notifications-tab" role="tab" aria-controls="v-pills-notifications" aria-selected="false">通知設定</a>
  <a href=<%=settings_terms_path%> class="nav-link" id="v-pills-terms-tab" role="tab" aria-controls="v-pills-terms" aria-selected="false">利用規約</a>
  <a href=<%=settings_inquiry_path%> class="nav-link" id="v-pills-inquiry-tab" role="tab" aria-controls="v-pills-inquiry" aria-selected="false">お問い合わせ</a>
</div>