config/routes.rb
Rails.application.routes.draw do
  
  root "records#new"
  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"
  get "signup", to: "users#new"

  resources :records, only: %i[index show new create update destroy]
  resources :users, only: %i[new create]
  get "games", to: "games#index"
  namespace :settings do
    get "statistics", to: "statistics#index"
    resources :wishlists, only: %i[index show create update destroy]
    get "notifications", to: "notifications#edit"
    patch "notifications", to: "notifications#update"
    get "terms", to: "terms#index"
    get "inquiry", to: "inquiry#new"
    post "inquiry", to: "inquiry#create"
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: %i[show destroy]

  def index
    @records = current_user.purchase_records.order(created_at: :desc)
  end

  def show

  end

  def new
    @record_form = PurchaseRecordForm.new
  end

  def create
    @record_form = PurchaseRecordForm.new(form_params)

    if @record_form.valid?
      game_id = @record_form.game_id
      game = current_user.available_games[game_id]
      amount = @record_form.amount
      comment = @record_form.comment

      current_user.record_purchase(game, amount, comment)

      flash[:success] = "記録しました"
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    record_id = params[:record_id].to_i
    record = current_user.purchase_records.find(record_id)
    update_params = {amount: params[:amount], comment: params[:comment]}

    if record.update(update_params)
      render json: { status: :ok } 
    else
      render json: { error: record.errors, status: :unprocessable_entity } 
    end
  end

  def destroy
    @record.destroy!
    flash[:danger] = "削除しました"
    redirect_to records_path
  end

  private

  def form_params
    conv_params = params.require(:purchase_record_form).permit(:game_id, :amount, :comment)
    conv_params[:game_id] = conv_params[:game_id].to_i
    conv_params[:amount] = conv_params[:amount].to_i
    conv_params[:user_id] = current_user.id
    return conv_params
  end

  def set_record
    @record = PurchaseRecord.find(params[:id])
  end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/index.html.erb
<div class="container mt-5">
  <h1>課金記録一覧</h1>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>ゲーム名</th>
        <th>金額</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @records.each do |record| %>
        <tr>
          <td>
            <%=link_to record.game_title, record_path(record), class:"text-decoration-none" %>
          </td>
          <td>
            <span class="badge bg-primary" data-bs-toggle="tooltip" title="金額">
              <%= record.amount %>
            </span>
          </td>
          <td>
            <%= link_to record_path(record), data: { turbo_method: :delete, confirm: "削除しますか？" }, class: "text-decoration-none" do%>
              <i class="fa-solid fa-trash"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/records/new.html.erb
<div class="container py-4 mb-4">
  <%=link_to records_path, style: "color: inherit; text-decoration: none;" do%>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">合計金額</h5>
        <h3 class="card-text"><%=sum_amount(current_user)%></h3>
      </div>
    </div>
  <% end %>
</div>

<div class="container">
  <%= form_with(model: @record_form, url: records_path, method: :post) do |form| %>
    <div class="form-group">
      <%= form.label :game %>
      <div class="position-relative">
        <input class="col-12 form-control" type="text" id="purchase_record_form_game">
      </div>
      <div>
        <%= form.number_field :game_id, class: "d-none", id: "game-id-field", value:"-1"%>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :amount %>
      <%= form.number_field :amount, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :comment %>
      <%= form.text_area :comment, class: "form-control" %>
    </div>

    <%= form.submit t('defaults.send'), class: "btn btn-primary" %>

  <% end %>
</div>

<script src="https://cdn.jsdelivr.net/npm/@tarekraafat/autocomplete.js@10.2.7/dist/autoComplete.min.js"></script>

app/views/records/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <div class="card">
        <div class="card-header bg-primary text-white">
          <h3><%= @record.game_title %> - Details</h3>
        </div>
        <div class="card-body">
          <div class="mb-4">
            <h4>タイトル</h4>
            <p class="lead"><%= @record.game_title %></p>
          </div>
          <div class="mb-4" id="amount-block">
            <h4>金額</h4>
            <div class="d-flex justify-content-between align-items-center">
              <p class="display-4 text-success mb-0" id="amount-value">
                <%= @record.amount %>
              </p>
              <div class="og-button" id="amount-edit">
                <i class="fas fa-pen-to-square" style="font-size: 24px;"></i>
              </div>
            </div>
          </div>
          <div class="mb-4">
            <h4>コメント</h4>
            <blockquote class="blockquote">
              <p><%= @record.comment %></p>
              <footer class="blockquote-footer">User Comment</footer>
            </blockquote>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>